/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./components/icons/Logo.vue')['default']
    Pets: typeof import('./components/Pets.vue')['default']
    Registry: typeof import('./components/Pets.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Telegram: typeof import('./components/icons/Telegram.vue')['default']
    Vk: typeof import('./components/icons/Vk.vue')['default']
    Whatsapp: typeof import('./components/icons/Whatsapp.vue')['default']
  }
}
